/*
 * Generated by scripts/geocode-events.mjs. Do not edit by hand; run the script.
 *
 * City-level coordinates for every event with a known city, looked up once
 * and committed, so nothing calls a geocoder at build or request time. Each
 * row keeps the city and country it came from, and coordsFor in lib/events.js
 * ignores a row whose place no longer matches the entry.
 */
export const EVENT_COORDS = {
  "dotdev": {
    "city": "Toronto",
    "country": "Canada",
    "lat": 43.6535,
    "lng": -79.3839
  },
  "the-wide-event": {
    "city": "Paris",
    "country": "France",
    "lat": 48.8589,
    "lng": 2.32
  },
  "shop-quest": {
    "city": "Bengaluru",
    "country": "India",
    "lat": 12.9768,
    "lng": 77.5901
  },
  "merchant-inspiration-talks": {
    "city": "Berlin",
    "country": "Germany",
    "lat": 52.5174,
    "lng": 13.3951
  },
  "shopx": {
    "city": "Ho Chi Minh City",
    "country": "Vietnam",
    "lat": 10.7737,
    "lng": 106.7166
  },
  "shoptalk-us": {
    "city": "Las Vegas",
    "country": "USA",
    "lat": 36.1674,
    "lng": -115.1484
  },
  "shoptalk-europe": {
    "city": "Barcelona",
    "country": "Spain",
    "lat": 41.3826,
    "lng": 2.1771
  },
  "shoptalk-luxe": {
    "city": "Abu Dhabi",
    "country": "UAE",
    "lat": 24.4538,
    "lng": 54.3774
  },
  "web-summit": {
    "city": "Lisbon",
    "country": "Portugal",
    "lat": 38.7078,
    "lng": -9.1366
  },
  "worldef-antalya": {
    "city": "Antalya",
    "country": "Türkiye",
    "lat": 36.8866,
    "lng": 30.703
  },
  "worldef-dubai": {
    "city": "Dubai",
    "country": "UAE",
    "lat": 25.2647,
    "lng": 55.2924
  },
  "worldef-istanbul": {
    "city": "Istanbul",
    "country": "Türkiye",
    "lat": 41.0064,
    "lng": 28.9759
  },
  "ecommerce-berlin-expo": {
    "city": "Berlin",
    "country": "Germany",
    "lat": 52.5174,
    "lng": 13.3951
  },
  "ecommerce-expo-london": {
    "city": "London",
    "country": "UK",
    "lat": 51.5074,
    "lng": -0.1278
  },
  "dmexco": {
    "city": "Cologne",
    "country": "Germany",
    "lat": 50.9384,
    "lng": 6.96
  },
  "ecomexpo-vilnius": {
    "city": "Vilnius",
    "country": "Lithuania",
    "lat": 54.687,
    "lng": 25.2829
  },
  "accelerate": {
    "city": "Salt Lake City",
    "country": "USA",
    "lat": 40.7596,
    "lng": -111.8868
  },
  "acquiror-conference": {
    "city": "New York",
    "country": "USA",
    "lat": 40.7127,
    "lng": -74.006
  },
  "camp-commerce": {
    "city": "Southampton, NY",
    "country": "USA",
    "lat": 40.8842,
    "lng": -72.3897
  },
  "ecom-elevated": {
    "city": "Salt Lake City",
    "country": "USA",
    "lat": 40.7596,
    "lng": -111.8868
  },
  "a-new-era": {
    "city": "London",
    "country": "UK",
    "lat": 51.5074,
    "lng": -0.1278
  },
  "suitetalks-shoptalk": {
    "city": "Las Vegas",
    "country": "USA",
    "lat": 36.1674,
    "lng": -115.1484
  },
  "ecomm-connect-denver": {
    "city": "Denver",
    "country": "USA",
    "lat": 39.7392,
    "lng": -104.9849
  },
  "ecom-collab-club": {
    "city": "London",
    "country": "UK",
    "lat": 51.5074,
    "lng": -0.1278
  },
  "dtc-dines-vancouver": {
    "city": "Vancouver",
    "country": "Canada",
    "lat": 49.2609,
    "lng": -123.114
  },
  "dtc-dines-nyc": {
    "city": "Brooklyn, NY",
    "country": "USA",
    "lat": 40.6526,
    "lng": -73.9497
  },
  "dotdigital-summit": {
    "city": "London",
    "country": "UK",
    "lat": 51.5074,
    "lng": -0.1278
  },
  "stowe-vt-ecommerce": {
    "city": "Stowe, VT",
    "country": "USA",
    "lat": 44.4644,
    "lng": -72.6856
  },
  "digital-commerce-today-boston": {
    "city": "Boston",
    "country": "USA",
    "lat": 42.3588,
    "lng": -71.0578
  }
};
