#!/usr/bin/env node
/*
 * Geocode every event city once and write the answers into
 * lib/eventCoords.js, which is committed. Nothing geocodes at request time
 * and nothing geocodes during `next build`: a build that depends on a third
 * party's uptime is a build that fails for reasons unrelated to the change,
 * and the coordinates of Lisbon do not move between deploys.
 *
 * Run it after adding an event or changing a city:
 *
 *   node scripts/geocode-events.mjs           # only what is missing or stale
 *   node scripts/geocode-events.mjs --all     # redo everything
 *
 * Each stored row keeps the city and country it was looked up from. If an
 * entry's place changes, lib/events.js stops applying the old coordinates
 * (coordsFor checks both) until this is run again, so a moved event is never
 * shown at the distance of its old city.
 *
 * Nominatim (OpenStreetMap) asks for one request a second and an identifying
 * user agent, and both are honoured here. City level is the precision: it is
 * what the entries record, and it is enough for "which of these is near me".
 */
import { readFileSync, writeFileSync, mkdtempSync, cpSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join, dirname } from "path";
import { fileURLToPath, pathToFileURL } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "lib/eventCoords.js");
const all = process.argv.includes("--all");

/* lib/ uses extensionless imports, which plain node will not resolve, so load
   the catalogue from a temp copy with the two imports it needs rewritten. */
async function loadEvents() {
  const dir = mkdtempSync(join(tmpdir(), "svt-geo-"));
  try {
    for (const f of ["events.js", "drafts.js"]) cpSync(join(root, "lib", f), join(dir, f.replace(".js", ".mjs")));
    const ev = join(dir, "events.mjs");
    writeFileSync(ev, readFileSync(ev, "utf8").replace(/from "\.\/drafts"/, 'from "./drafts.mjs"').replace(/^import .*eventCoords.*$/m, "const COORDS = {};"));
    const m = await import(pathToFileURL(ev).href);
    return m.ALL_EVENTS;
  } finally { rmSync(dir, { recursive: true, force: true }); }
}

function loadExisting() {
  try {
    const src = readFileSync(OUT, "utf8");
    const json = src.slice(src.indexOf("{", src.indexOf("EVENT_COORDS")), src.lastIndexOf("}") + 1);
    return JSON.parse(json);
  } catch { return {}; }
}

const COUNTRY = { UK: "United Kingdom", USA: "United States", UAE: "United Arab Emirates" };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function geocode(city, country) {
  const q = new URLSearchParams({ city, country: COUNTRY[country] || country, format: "json", limit: "1" });
  const res = await fetch(`https://nominatim.openstreetmap.org/search?${q}`, {
    headers: { "User-Agent": "watchfor.tools event geocoder (https://watchfor.tools/contact)" },
  });
  if (!res.ok) throw new Error(`nominatim ${res.status}`);
  const [hit] = await res.json();
  if (!hit) return null;
  return { lat: Math.round(Number(hit.lat) * 1e4) / 1e4, lng: Math.round(Number(hit.lon) * 1e4) / 1e4 };
}

const events = await loadEvents();
const existing = loadExisting();
const out = {};
let looked = 0, kept = 0, missing = [];

for (const e of events) {
  const city = String(e.city || "").trim();
  const country = String(e.country || "").trim();
  if (!city || !country || /^n\/a$/i.test(country)) continue;
  const prev = existing[e.id];
  if (!all && prev && prev.city === city && prev.country === country) { out[e.id] = prev; kept++; continue; }
  // City strings like "Southampton, NY" carry their region; Nominatim's
  // structured `city` wants the bare name, so try that first, then free text.
  const bare = city.split(",")[0].trim();
  let hit = await geocode(bare, country);
  await sleep(1100);
  if (!hit) {
    const res = await fetch(`https://nominatim.openstreetmap.org/search?${new URLSearchParams({ q: `${city}, ${COUNTRY[country] || country}`, format: "json", limit: "1" })}`,
      { headers: { "User-Agent": "watchfor.tools event geocoder (https://watchfor.tools/contact)" } });
    const [h] = res.ok ? await res.json() : [];
    hit = h ? { lat: Math.round(Number(h.lat) * 1e4) / 1e4, lng: Math.round(Number(h.lon) * 1e4) / 1e4 } : null;
    await sleep(1100);
  }
  looked++;
  if (!hit) { missing.push(`${e.id} (${city}, ${country})`); continue; }
  out[e.id] = { city, country, ...hit };
  console.log(`${e.id.padEnd(32)} ${city}, ${country} -> ${hit.lat}, ${hit.lng}`);
}

const body = `/*
 * Generated by scripts/geocode-events.mjs. Do not edit by hand; run the script.
 *
 * City-level coordinates for every event with a known city, looked up once
 * and committed, so nothing calls a geocoder at build or request time. Each
 * row keeps the city and country it came from, and coordsFor in lib/events.js
 * ignores a row whose place no longer matches the entry.
 */
export const EVENT_COORDS = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(OUT, body);
console.log(`\n${Object.keys(out).length} stored (${looked} looked up, ${kept} kept).`);
if (missing.length) console.log(`No result for: ${missing.join(", ")}`);
